language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t feed-service ./services/feed-service
  - docker build -t frontend-service ./services/frontend-service
  - docker build -t reverseproxy-service ./services/reverseproxy-service
  - docker build -t user-service ./services/user-service
  - docker tag feed-service charizard117/feed-service:v4
  - docker tag frontend-service charizard117/frontend-service:v11
  - docker tag reverseproxy-service charizard117/reverseproxy-service:v7
  - docker tag user-service charizard117/user-service:v4

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push charizard117/feed-service:v4
  - docker push charizard117/frontend-service:v11
  - docker push charizard117/reverseproxy-service:v7
  - docker push charizard117/user-service:v4
