version: "1.1"
services:
  reverseproxy:
    image: reverseproxy-service
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - user-service
      - feed-service
  user-service:
    image: user-service
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://ae54a20fdd5c84175a9c0528083d7e47-1861523572.us-east-1.elb.amazonaws.com:8100"
  feed-service:
    image: feed-service
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://ae54a20fdd5c84175a9c0528083d7e47-1861523572.us-east-1.elb.amazonaws.com:8100"
  frontend-service:
    image: frontend-service:v4
    ports:
      - "8100:80"
