apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    run: frontend-service
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 80
  selector:
    run: frontend-service
