apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-service
  labels:
    service: reverseproxy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy-service
  template:
    metadata:
      labels:
        service: reverseproxy-service
    spec:
      containers:
        - image: charizard117/reverseproxy-service:v7
          name: reverseproxy-service
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      restartPolicy: Always
