apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy-service
  name: reverseproxy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: reverseproxy-service
  template:
    metadata:
      labels:
        run: reverseproxy-service
    spec:
      containers:
        - image: charizard117/reverseproxy-service:v3
          name: reverseproxy-service
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
      restartPolicy: Always
