apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    service: user-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: user-service
